name: Compiler-Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - name: Do test(C)
      run: cd compiler; make test
    - name: Do test(sh)
      run: cd compiler; make test-sh
